spring:
  application:
    name: be-session

  datasource:
    url: jdbc:mysql://localhost:3306/likelion?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: gang0131
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto : update

cors:
  allowed-origins: http://localhost:3000, http://localhost:5173

jwt:
  secret : V7mQp9xR2sK8zN4bY6tHcL3wE5uJfA1dG9rXp2qW
  access-token-expiration : 1800000

logging :
  level :
    root : INFO
    com.example.likelionkang : DEBUG